language: c
compiler: gcc
before_install:
    - export PERL_MM_USE_DEFAULT=1
    - export PERL5LIB=/home/travis/perl5/lib/perl5
install: cpanm --notest Template
script: cd Sample && make && make test
